[package]
name = "serde_test"
<<<<<<< HEAD
version = "0.9.13" # remember to update html_root_url
||||||| merged common ancestors
version = "0.9.13"
=======
version = "0.9.14"
>>>>>>> origin/master
authors = ["Erick Tryzelaar <erick.tryzelaar@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Token De/Serializer for testing De/Serialize implementations"
homepage = "https://serde.rs"
repository = "https://github.com/serde-rs/serde"
documentation = "https://docs.serde.rs/serde_test/"
keywords = ["serde", "serialization"]
readme = "README.md"
include = ["Cargo.toml", "src/**/*.rs", "README.md", "LICENSE-APACHE", "LICENSE-MIT"]
publish = false # this branch contains breaking changes

[dependencies]
serde = { version = "0.9", path = "../serde" }

[badges]
travis-ci = { repository = "serde-rs/serde" }
